application: python-ok
version: 10
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

skip_files: |
  ^(.*/)?(
  (#.*#)|
  (.*~)|
  (.*\.py[co])|
  (.*/RCS/.*)|
  (\..*)|
  (.*/\.svn/.*)|
  (.*/Thumbs\.db)|
  (.*/\.svn/.*)|
  (node_modules)|
  )$

libraries:
- name: django
  version: latest

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static/admin
  static_dir: django/contrib/admin/static/admin
  expiration: '0'

- url: /static/dict/pkg
  static_dir: release/static/dict/pkg
  expiration: '0'

- url: /static/dict
  static_dir: dict/static/dict
  expiration: '0'

- url: /static
  static_dir: resources/static
  expiration: '0'

- url: /.*
  script: djangoappengine.main.application
